name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Docker build test
        run: docker build -t ocr-app .
      
      - name: Test Docker container runs
        run: docker run --rm ocr-app python app.py --version

      - name: Run tests
        run: pytest

  deploy:
    # Este job se ejecuta solo si las pruebas pasan y únicamente en la rama "main"
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Package Application
        run: |
          zip -r package.zip app.py requirements.txt README.md

      - name: Deploy (placeholder)
        run: |
          echo "Aquí implementa el despliegue, por ejemplo, subir el paquete a un servidor o S3."